// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4qcLKWCNffFSZK9Y6LWM-NknNa_bzU9g',
    appId: '1:168874557598:web:d335e3e066bee623303b8f',
    messagingSenderId: '168874557598',
    projectId: 'braindump-1e567',
    authDomain: 'braindump-1e567.firebaseapp.com',
    storageBucket: 'braindump-1e567.firebasestorage.app',
    measurementId: 'G-JCZR64PTYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY1chwEjoso0nBQkPadro37yj_BFits5g',
    appId: '1:168874557598:android:e0b57166965dd8af303b8f',
    messagingSenderId: '168874557598',
    projectId: 'braindump-1e567',
    storageBucket: 'braindump-1e567.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLrCjQ4yo4aI66zhF2MTcBs8O0JRP2vjs',
    appId: '1:168874557598:ios:67124a8e00f1b41e303b8f',
    messagingSenderId: '168874557598',
    projectId: 'braindump-1e567',
    storageBucket: 'braindump-1e567.firebasestorage.app',
    iosBundleId: 'com.example.bdAppV0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLrCjQ4yo4aI66zhF2MTcBs8O0JRP2vjs',
    appId: '1:168874557598:ios:67124a8e00f1b41e303b8f',
    messagingSenderId: '168874557598',
    projectId: 'braindump-1e567',
    storageBucket: 'braindump-1e567.firebasestorage.app',
    iosBundleId: 'com.example.bdAppV0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4qcLKWCNffFSZK9Y6LWM-NknNa_bzU9g',
    appId: '1:168874557598:web:27b6d7d9cd4479f9303b8f',
    messagingSenderId: '168874557598',
    projectId: 'braindump-1e567',
    authDomain: 'braindump-1e567.firebaseapp.com',
    storageBucket: 'braindump-1e567.firebasestorage.app',
    measurementId: 'G-Q2ZTR9DER0',
  );
}
